In [30]:
# Multiple Linear Regression을 구현해 봥요
# scikit-learn 으로 구현해서 특정 데이터로 prediction까지

import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn.preprocessing import MinMaxScaler
# Ras Data Loading
original = pd.read_csv('/content/drive/MyDrive/빅데이터 과정 폴더/data/ozone/ozone.csv')
display(original)

df1 = original[['Solar.R','Wind','Temp','Ozone']]
display(df1)

# 데이터 전처리
# 결측치 처리
df2 = df1.dropna(how='any')
display(df2)
#이상치 처리
import numpy as np
import matplotlib.pyplot as plt
#정규화 처리
scaler_x = MinMaxScaler()
scaler_t = MinMaxScaler()
#scikit-learn구현은 정규화처리를 하지 않아도 되요
#내부적으로 정규화 처리가 진행되요
# scaler에게 최대값과 최소값을 알려줘요!
scaler_x.fit(df2.drop('Ozone', axis=1, inplace = False))
scaler_t.fit(df2['Ozone'].values.reshape(-1,1))
#Traning Data Set을 정의
# x_data = df2.drop('Ozone', axis=1, inplace=False).values
# t_data = df2['Ozone'].values.reshape(-1,1)
x_data = scaler_x.transform(df2.drop('Ozone',axis=1, inplace=False))
t_data = scaler_t.transform(df2['Ozone'].values.reshape(-1,1))

# Model 만들고 학습을 진행

sklearn_model =linear_model.LinearRegression()

sklearn_model.fit(x_data, t_data)

sklearn_model.predict([[130,10,70]])
#array([[25.74518848]])

Ozone  Solar.R  Wind  Temp  Month  Day
0     41.0    190.0   7.4    67      5    1
1     36.0    118.0   8.0    72      5    2
2     12.0    149.0  12.6    74      5    3
3     18.0    313.0  11.5    62      5    4
4      NaN      NaN  14.3    56      5    5
..     ...      ...   ...   ...    ...  ...
148   30.0    193.0   6.9    70      9   26
149    NaN    145.0  13.2    77      9   27
150   14.0    191.0  14.3    75      9   28
151   18.0    131.0   8.0    76      9   29
152   20.0    223.0  11.5    68      9   30

[153 rows x 6 columns]

Solar.R  Wind  Temp  Ozone
0      190.0   7.4    67   41.0
1      118.0   8.0    72   36.0
2      149.0  12.6    74   12.0
3      313.0  11.5    62   18.0
4        NaN  14.3    56    NaN
..       ...   ...   ...    ...
148    193.0   6.9    70   30.0
149    145.0  13.2    77    NaN
150    191.0  14.3    75   14.0
151    131.0   8.0    76   18.0
152    223.0  11.5    68   20.0

[153 rows x 4 columns]

Solar.R  Wind  Temp  Ozone
0      190.0   7.4    67   41.0
1      118.0   8.0    72   36.0
2      149.0  12.6    74   12.0
3      313.0  11.5    62   18.0
6      299.0   8.6    65   23.0
..       ...   ...   ...    ...
147     20.0  16.6    63   14.0
148    193.0   6.9    70   30.0
150    191.0  14.3    75   14.0
151    131.0   8.0    76   18.0
152    223.0  11.5    68   20.0

[111 rows x 4 columns]

array([[39.38342115]])

In [35]:
#위의 문제를 Tensorflow Keras로 구현해서
# [[130,10,70]] 데이터에 대한 오존량의 예측값 구해보기

#model 구현
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import SGD

keras_model = Sequential()

keras_model.add(Flatten(input_shape=(3,)))

output_layer = Dense(units=1,
                      activation='linear')
keras_model.add(output_layer)

keras_model.compile(optimizer=SGD(learning_rate=1e-2),
                    loss='mse')

keras_model.fit(x_data,
                t_data,
                epochs=1000)

my_data = np.array([[130, 10, 70]])
my_data_norm = scaler_x.transform(my_data)

# 이렇게 예측할때도 정규화된 데이터를 넣어서 예측을 수행해야 해요!
result = keras_model.predict(my_data_norm)
real_result = scaler_t.inverse_transform(result)

print(real_result)
#[[25.008686]

Epoch 1/1000
4/4 [==============================] - 0s 5ms/step - loss: 0.0516
Epoch 2/1000
4/4 [==============================] - 0s 5ms/step - loss: 0.0500
Epoch 3/1000
4/4 [==============================] - 0s 5ms/step - loss: 0.0487
Epoch 4/1000
4/4 [==============================] - 0s 7ms/step - loss: 0.0476
Epoch 5/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0465
Epoch 6/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0457
Epoch 7/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0451
Epoch 8/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0444
Epoch 9/1000
4/4 [==============================] - 0s 5ms/step - loss: 0.0439
Epoch 10/1000
4/4 [==============================] - 0s 5ms/step - loss: 0.0435
Epoch 11/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0431
Epoch 12/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0427
Epoch 13/1000
4/4 [==============================

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
